IMDB_WebApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IMDB_WebApp.Models
{
    public class Movie
    {
        public Movie()
        {
            Actors = new List<Actor>();
        }
        #region Properties
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [Column(TypeName ="datetime2")]
        public DateTime ReleaseDate { get; set; }
        public string Bio { get; set; }
        public string Photo { get; set; }
        public string AlternateText { get; set; }
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer{ get; set; }
        #endregion
        //List of all actors in the movie
        public virtual ICollection<Actor> Actors { get; set; }
    }
}

IMDB_WebApp/Models/MovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMDB_WebApp.Models
{
    public class MovieViewModel
    {
        public int MovieId { get; set; }
        public string Name { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int ProducerId { get; set; }
        public virtual ICollection<AssignedActor> Actors { get; set; }
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        
    }
}

IMDB_WebApp/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMDB_WebApp;
using IMDB_WebApp.Models;

namespace IMDB_WebApp.Controllers
{
    public class ActorsController : Controller
    {
        private DbContextIMDB db = new DbContextIMDB();
        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DOB,Sex,Bio")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Actors.Add(actor);
                db.SaveChanges();
                return RedirectToAction("Index","Movie");
            }

            return View(actor);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMDB_WebApp/Controllers/ProducersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMDB_WebApp;
using IMDB_WebApp.Models;

namespace IMDB_WebApp.Controllers
{
    public class ProducersController : Controller
    {
        private DbContextIMDB db = new DbContextIMDB();


        // GET: Producers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProducerId,Name,Sex,Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                db.Producers.Add(producer);
                db.SaveChanges();
                return RedirectToAction("Index", "Movie");
            }

            return View(producer);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMDB_WebApp/Views/Movie/Create.cshtml
@model IMDB_WebApp.Models.Movie

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProducerId, "ProducerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProducerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProducerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IMDB_WebApp/Views/Movie/CreateMovie.cshtml
@model MovieViewModel
@using IMDB_WebApp.Models

@using (Html.BeginForm("CreateMovie","Movie",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProducerId, "ProducerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProducerId", (SelectList)ViewBag.ProducerId, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div id="checkBoxes">
                @Html.EditorFor(model => model.Actors)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="file" name="ImageFile" accept="image/x-png,image/gif,image/jpeg" required />
            </div>
       </div>
            <script>
                console.log("Verify if there is at least one checkbox that is checked or not");
            </script>
</fieldset>
    <p>
        <input type="submit" value="Create" />
    </p>
    <div>
        @Html.ActionLink("Back to List", "Index")
        @Html.ActionLink("Create New Actor","Create","Actors")
        @Html.ActionLink("Create New Producer","Create","Producers")
    </div>
}

IMDB_WebApp/Views/Movie/Details.cshtml
@model MovieDetailsViewModel
@using IMDB_WebApp.Models

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ProducerName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ProducerName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Actors)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Actors)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ReleaseDate)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ReleaseDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Photo)
    </dt>
    <dd>
        <img src="@Url.Content(Model.Photo)" alt="There is no image for this Movie" width="250" height="250"/>
    </dd>
</dl>

IMDB_WebApp/Views/Movie/EditMovie.cshtml
@model  MovieEditViewModel
@using  IMDB_WebApp.Models


@using (Html.BeginForm("EditMovie","Movie",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class="control-label col-md-2"})
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "text", required = "required" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProducerId, "ProducerId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProducerId", (SelectList)ViewBag.ProducerId, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.EditorFor(model => model.Actors)
    </div>
    <div class="form-group">
        <img src="@Url.Content(Model.Photo)" alt="There is no image for this Movie" width="250" height="250" />
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="file" name="ImageFile" accept="image/x-png,image/gif,image/jpeg"/>
        </div>
    </div>
<p>
    <input type = "Submit" value = "SaveChanges" />
</p>

}

IMDB_WebApp/Views/Movie/Index.cshtml
@model IEnumerable<IMDB_WebApp.Models.Movie>

<p>
    @Html.ActionLink("Create New", "CreateMovie")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Producer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Producer.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditMovie", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
        </td>
    </tr>
}

</table>